package it.polimi.ingsw.model;

public enum Error {
    NOT_FREE,
    NOT_ADJACENT,
    INVALID_LEVEL_MOVE,
    INVALID_LEVEL_BUILD,
    IS_DOME,
    MOVE_AFTER_BUILD,
    BUILD_BEFORE_MOVE,
    BUILDS_EXCEEDED,
    MOVES_EXCEEDED,
    BLOCK_MOVE_UP,
    CANT_DOME_UNDERFOOT,
    SAME_DIRECTION_NOT_FREE
}
