package it.polimi.ingsw.model;

public enum Error {
    NOT_FREE,
    NOT_ADJACENT,
    INVALID_LEVEL_MOVE,
    INVALID_LEVEL_BUILD,
    IS_DOME,
    MOVE_AFTER_BUILD,
    BUILD_BEFORE_MOVE,
    BUILDS_EXCEEDED,
    MOVES_EXCEEDED,
    BLOCK_MOVE_UP,
    CANT_DOME_UNDERFOOT,
    SAME_DIRECTION_NOT_FREE,
    EXTRA_BUILD_NOT_PERIMETER,
    EXTRA_BUILD_NOT_SAME_SPACE,
    EXTRA_BUILD_ONLY_SAME_SPACE,
    EXTRA_MOVE_NOT_BACK,
    CANT_MOVE_UP
}
